---
title: "Feature Hashing Kuhn"
author: "Niccolò Salvini"
output: github_document
---


```{r sources, message=FALSE, echo=FALSE}
source("libs.R")
```

# Simple Feature Hashing
```{r}
data = source_data("https://github.com/topepo/FES/blob/master/Data_Sets/OkCupid/okc.RData?raw=True")
```
 

## Make small example data set


```{r}
sample_towns = c(
  'alameda', 'belmont', 'benicia', 'berkeley', 'castro_valley', 'daly_city', 
  'emeryville', 'fairfax', 'martinez', 'menlo_park', 'mountain_view', 'oakland', 
  'other', 'palo_alto', 'san_francisco', 'san_leandro', 'san_mateo', 
  'san_rafael', 'south_san_francisco', 'walnut_creek'
)

location  =
  okc_train %>% 
  dplyr::select(where_town) %>% 
  distinct(where_town) %>% 
  arrange(where_town)

```


##  Create hash features using binary representations

```{r}
binary_hashes <-
  hashed.model.matrix(
    ~ where_town,
    data = location,
    hash.size = 2 ^ 4,
    signed.hash = FALSE,
    create.mapping = TRUE
  )

binary_hashes

```

## Binary mapping

```{r}
binary_mapping <- hash.mapping(binary_hashes)
names(binary_mapping) <- str_remove(names(binary_mapping), "where_town")
binary_calcs <- 
  binary_mapping %>% 
  enframe() %>% 
  set_names(c("town", "column_num_16")) %>% 
  mutate(integer_16 = hashed.value(names(binary_mapping))) %>% 
  dplyr::filter(town %in% sample_towns) %>% 
  arrange(town)

binary_calcs
```


```{r}
binary_df <- 
  binary_hashes %>% 
  as.matrix() %>% 
  as_tibble() %>% 
  bind_cols(location) %>% 
  dplyr::rename(town = where_town) %>% 
  dplyr::filter(town %in% sample_towns) %>% 
  arrange(town)

binary_df %>%
  kable() 

```



## signed hash

```{r}
signed_hashes <-
  hashed.model.matrix(
    ~ where_town,
    data = location,
    hash.size = 2 ^ 4,
    signed.hash = TRUE
  )

signed_df = 
  signed_hashes %>% 
  as.matrix() %>% 
  as_tibble() %>% 
  bind_cols(location) %>% 
  dplyr::rename(town = where_town) %>% 
  dplyr::filter(town %in% sample_towns) %>% 
  arrange(town)
 
signed_df %>% 
  kable()

```
